version: '3.8'

services:
  app:
    image: personaldemo
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
      - postgres
      - h2

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  h2:
    image: oscarfonts/h2:latest
    environment:
      H2_OPTIONS: '-tcp -tcpAllowOthers -ifNotExists'
    ports:
      - "1521:1521"